#include "Map.hpp"
#include "Building.hpp"
#include "Point.hpp"
#include "Tile.hpp"

namespace game {
Map *Map::instance = nullptr;

Map::Map() {

players={};
tiles={};
roadsInMap={};
  // Crate Tiles for map
  Tile *tile1 = new Tile(Resource::Iron, 0, 10);
  Tile *tile2 = new Tile(Resource::Wool, 1, 2);
  Tile *tile3 = new Tile(Resource::Wood, 2, 9);
  Tile *tile4 = new Tile(Resource::Wheat, 3, 12);
  Tile *tile5 = new Tile(Resource::Brick, 4, 6);
  Tile *tile6 = new Tile(Resource::Wool, 5, 4);
  Tile *tile7 = new Tile(Resource::Brick, 6, 10);
  Tile *tile8 = new Tile(Resource::Wheat, 7, 9);
  Tile *tile9 = new Tile(Resource::Wood, 8, 11);
  Tile *tile10 = new Tile(Resource::None, 9, 0);
  Tile *tile11 = new Tile(Resource::Wood, 10, 3);
  Tile *tile12 = new Tile(Resource::Iron, 11, 8);
  Tile *tile13 = new Tile(Resource::Wood, 12, 8);
  Tile *tile14 = new Tile(Resource::Iron, 13, 3);
  Tile *tile15 = new Tile(Resource::Wheat, 14, 4);
  Tile *tile16 = new Tile(Resource::Wool, 15, 5);
  Tile *tile17 = new Tile(Resource::Brick, 16, 5);
  Tile *tile18 = new Tile(Resource::Wheat, 17, 6);
  Tile *tile19 = new Tile(Resource::Wool, 18, 11);

  addTile(tile1);
  addTile(tile2);
  addTile(tile3);
  addTile(tile4);
  addTile(tile5);
  addTile(tile6);
  addTile(tile7);
  addTile(tile8);
  addTile(tile9);
  addTile(tile10);
  addTile(tile11);
  addTile(tile12);
  addTile(tile13);
  addTile(tile14);
  addTile(tile15);
  addTile(tile16);
  addTile(tile17);
  addTile(tile18);
  addTile(tile19);

  // create Points for map
  Point point1(BuildingType::None);
  point1.addTile(tile1);
  Point point2(BuildingType::None);
  point2.addTiles({tile1});
  Point point3(BuildingType::None);
  point3.addTiles({tile1, tile2});
  Point point4(BuildingType::None);
  point4.addTiles({tile2});
  Point point5(BuildingType::None);
  point5.addTiles({tile2, tile3});
  Point point6(BuildingType::None);
  point6.addTiles({tile3});
  Point point7(BuildingType::None);
  point7.addTiles({tile3});
  Point point8(BuildingType::None);
  point8.addTiles({tile4});
  Point point9(BuildingType::None);
  point9.addTiles({tile1, tile4});
  Point point10(BuildingType::None);
  point10.addTiles({tile1, tile4, tile5});
  Point point11(BuildingType::None);
  point11.addTiles({tile1, tile2, tile5});
  Point point12(BuildingType::None);
  point12.addTiles({tile2, tile5, tile6});
  Point point13(BuildingType::None);
  point13.addTiles({tile2, tile3, tile6});
  Point point14(BuildingType::None);
  point14.addTiles({tile3, tile6, tile7});
  Point point15(BuildingType::None);
  point15.addTiles({tile3, tile7});
  Point point16(BuildingType::None);
  point16.addTiles({tile7});
  Point point17(BuildingType::None);
  point17.addTiles({tile8});
  Point point18(BuildingType::None);
  point18.addTiles({tile4, tile8});
  Point point19(BuildingType::None);
  point19.addTiles({tile4, tile8, tile9});
  Point point20(BuildingType::None);
  point20.addTiles({tile4, tile5, tile9});
  Point point21(BuildingType::None);
  point21.addTiles({tile5, tile9, tile10});
  Point point22(BuildingType::None);
  point22.addTiles({tile5, tile6, tile10});
  Point point23(BuildingType::None);
  point23.addTiles({tile6, tile10, tile11});
  Point point24(BuildingType::None);
  point24.addTiles({tile6, tile7, tile11});
  Point point25(BuildingType::None);
  point25.addTiles({tile7, tile11, tile12});
  Point point26(BuildingType::None);
  point26.addTiles({tile7, tile12});
  Point point27(BuildingType::None);
  point27.addTiles({tile12});
  Point point28(BuildingType::None);
  point28.addTiles({tile8});
  Point point29(BuildingType::None);
  point29.addTiles({tile8, tile13});
  Point point30(BuildingType::None);
  point30.addTiles({tile8, tile9, tile13});
  Point point31(BuildingType::None);
  point31.addTiles({tile9, tile13, tile14});
  Point point32(BuildingType::None);
  point32.addTiles({tile9, tile10, tile14});
  Point point33(BuildingType::None);
  point33.addTiles({tile10, tile14, tile15});
  Point point34(BuildingType::None);
  point34.addTiles({tile10, tile11, tile15});
  Point point35(BuildingType::None);
  point35.addTiles({tile11, tile15, tile16});
  Point point36(BuildingType::None);
  point36.addTiles({tile11, tile12, tile16});
  Point point37(BuildingType::None);
  point37.addTiles({tile12, tile16});
  Point point38(BuildingType::None);
  point38.addTiles({tile12});
  Point point39(BuildingType::None);
  point39.addTiles({tile13});
  Point point40(BuildingType::None);
  point40.addTiles({tile13, tile17});
  Point point41(BuildingType::None);
  point41.addTiles({tile13, tile14, tile17});
  Point point42(BuildingType::None);
  point42.addTiles({tile14, tile17, tile18});
  Point point43(BuildingType::None);
  point43.addTiles({tile14, tile15, tile18});
  Point point44(BuildingType::None);
  point44.addTiles({tile15, tile18, tile19});
  Point point45(BuildingType::None);
  point45.addTiles({tile15, tile16, tile19});
  Point point46(BuildingType::None);
  point46.addTiles({tile16, tile19});
  Point point47(BuildingType::None);
  point47.addTiles({tile16});
  Point point48(BuildingType::None);
  point48.addTiles({tile17});
  Point point49(BuildingType::None);
  point49.addTiles({tile17});
  Point point50(BuildingType::None);
  point50.addTiles({tile17, tile18});
  Point point51(BuildingType::None);
  point51.addTiles({tile18});
  Point point52(BuildingType::None);
  point52.addTiles({tile18, tile19});
  Point point53(BuildingType::None);
  point53.addTiles({tile19});
  Point point54(BuildingType::None);
  point54.addTiles({tile19});

  // build the neighbors
  point1.addNeighbor(point2);
  point1.addNeighbor(point9);
  point2.addNeighbor(point1);
  point2.addNeighbor(point3);
  point3.addNeighbor(point2);
  point3.addNeighbor(point4);
  point3.addNeighbor(point11);
  point4.addNeighbor(point3);
  point4.addNeighbor(point5);
  point5.addNeighbor(point4);
  point5.addNeighbor(point6);
  point5.addNeighbor(point13);
  point6.addNeighbor(point5);
  point6.addNeighbor(point7);
  point7.addNeighbor(point6);
  point7.addNeighbor(point15);
  point8.addNeighbor(point9);
  point8.addNeighbor(point18);
  point9.addNeighbor(point1);
  point9.addNeighbor(point8);
  point9.addNeighbor(point10);
  point10.addNeighbor(point9);
  point10.addNeighbor(point11);
  point10.addNeighbor(point20);
  point11.addNeighbor(point3);
  point11.addNeighbor(point10);
  point11.addNeighbor(point12);
  point12.addNeighbor(point11);
  point12.addNeighbor(point13);
  point12.addNeighbor(point22);
  point13.addNeighbor(point5);
  point13.addNeighbor(point12);
  point13.addNeighbor(point14);
  point14.addNeighbor(point13);
  point14.addNeighbor(point15);
  point14.addNeighbor(point24);
  point15.addNeighbor(point7);
  point15.addNeighbor(point14);
  point15.addNeighbor(point16);
  point16.addNeighbor(point15);
  point16.addNeighbor(point26);
  point17.addNeighbor(point18);
  point17.addNeighbor(point28);
  point18.addNeighbor(point8);
  point18.addNeighbor(point17);
  point18.addNeighbor(point19);
  point19.addNeighbor(point18);
  point19.addNeighbor(point20);
  point19.addNeighbor(point30);
  point20.addNeighbor(point10);
  point20.addNeighbor(point19);
  point20.addNeighbor(point21);
  point21.addNeighbor(point20);
  point21.addNeighbor(point22);
  point21.addNeighbor(point32);
  point22.addNeighbor(point12);
  point22.addNeighbor(point21);
  point22.addNeighbor(point23);
  point23.addNeighbor(point22);
  point23.addNeighbor(point24);
  point23.addNeighbor(point34);
  point24.addNeighbor(point14);
  point24.addNeighbor(point23);
  point24.addNeighbor(point25);
  point25.addNeighbor(point24);
  point25.addNeighbor(point26);
  point25.addNeighbor(point36);
  point26.addNeighbor(point16);
  point26.addNeighbor(point25);
  point26.addNeighbor(point27);
  point27.addNeighbor(point26);
  point27.addNeighbor(point38);
  point28.addNeighbor(point17);
  point28.addNeighbor(point29);
  point29.addNeighbor(point28);
  point29.addNeighbor(point30);
  point29.addNeighbor(point39);
  point30.addNeighbor(point19);
  point30.addNeighbor(point29);
  point30.addNeighbor(point31);
  point31.addNeighbor(point30);
  point31.addNeighbor(point32);
  point31.addNeighbor(point41);
  point32.addNeighbor(point21);
  point32.addNeighbor(point31);
  point32.addNeighbor(point33);
  point33.addNeighbor(point32);
  point33.addNeighbor(point34);
  point33.addNeighbor(point43);
  point34.addNeighbor(point23);
  point34.addNeighbor(point33);
  point34.addNeighbor(point35);
  point35.addNeighbor(point34);
  point35.addNeighbor(point36);
  point35.addNeighbor(point45);
  point36.addNeighbor(point25);
  point36.addNeighbor(point35);
  point36.addNeighbor(point37);
  point37.addNeighbor(point36);
  point37.addNeighbor(point38);
  point37.addNeighbor(point47);
  point38.addNeighbor(point27);
  point38.addNeighbor(point37);
  point39.addNeighbor(point29);
  point39.addNeighbor(point40);
  point40.addNeighbor(point39);
  point40.addNeighbor(point41);
  point40.addNeighbor(point48);
  point41.addNeighbor(point31);
  point41.addNeighbor(point40);
  point41.addNeighbor(point42);
  point42.addNeighbor(point41);
  point42.addNeighbor(point43);
  point42.addNeighbor(point50);
  point43.addNeighbor(point33);
  point43.addNeighbor(point42);
  point43.addNeighbor(point44);
  point44.addNeighbor(point43);
  point44.addNeighbor(point45);
  point44.addNeighbor(point52);
  point45.addNeighbor(point35);
  point45.addNeighbor(point44);
  point45.addNeighbor(point46);
  point46.addNeighbor(point45);
  point46.addNeighbor(point47);
  point46.addNeighbor(point54);
  point47.addNeighbor(point37);
  point47.addNeighbor(point46);
  point48.addNeighbor(point40);
  point48.addNeighbor(point49);
  point49.addNeighbor(point48);
  point49.addNeighbor(point50);
  point50.addNeighbor(point49);
  point50.addNeighbor(point51);
  point51.addNeighbor(point50);
  point51.addNeighbor(point52);
  point52.addNeighbor(point51);
  point52.addNeighbor(point53);
  point53.addNeighbor(point52);
  point53.addNeighbor(point54);
  point54.addNeighbor(point46);
  point54.addNeighbor(point53);
  addPoint(&point1);
  addPoint(&point2);
  addPoint(&point3);
  addPoint(&point4);
  addPoint(&point5);
  addPoint(&point6);
  addPoint(&point7);
  addPoint(&point8);
  addPoint(&point9);
  addPoint(&point10);
  addPoint(&point11);
  addPoint(&point12);
  addPoint(&point13);
  addPoint(&point14);
  addPoint(&point15);
  addPoint(&point16);
  addPoint(&point17);
  addPoint(&point18);
  addPoint(&point19);
  addPoint(&point20);
  addPoint(&point21);
  addPoint(&point22);
  addPoint(&point23);
  addPoint(&point24);
  addPoint(&point25);
  addPoint(&point26);
  addPoint(&point27);
  addPoint(&point28);
  addPoint(&point29);
  addPoint(&point30);
  addPoint(&point31);
  addPoint(&point32);
  addPoint(&point33);
  addPoint(&point34);
  addPoint(&point35);
  addPoint(&point36);
  addPoint(&point37);
  addPoint(&point38);
  addPoint(&point39);
  addPoint(&point40);
  addPoint(&point41);
  addPoint(&point42);
  addPoint(&point43);
  addPoint(&point44);
  addPoint(&point45);
  addPoint(&point46);
  addPoint(&point47);
  addPoint(&point48);
  addPoint(&point49);
  addPoint(&point50);
  addPoint(&point51);
  addPoint(&point52);
  addPoint(&point53);
  addPoint(&point54);

}

} // namespace game